# Usar una imagen base de Java (versión 17 en este caso)
FROM openjdk:21-jdk

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo JAR de la aplicación (generado por Maven)
COPY target/crud-0.0.1-SNAPSHOT.jar prueba.jar

# Exponer el puerto en el que corre la aplicación 8080
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "prueba.jar"]